### Objective

In this notebook, I will perform a full data cleaning process on a café sales dataset to prepare it for analysis.
The goal is to identify and fix any issues in the raw data such as missing values, wrong data types, or inconsistent entries.

##### Steps I Will Follow:
1-Load the dataset

2-Check for duplicates

3-Explore unique values in each column

4-Convert data types (numeric and datetime)

5-Handle missing values

6-Export the cleaned dataset

###  Importing the raw dataset into a DataFrame.
##### Here, I loaded the raw café sales data for cleaning and analysis and make some Explortation. 
the dataset source: (https://www.kaggle.com/datasets/ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training)

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(pd.read_csv(r"C:\Users\Pola\Downloads\New folder\dirty_cafe_sales.csv"))

In [3]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,NaN,UNKNOWN,UNKNOWN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06
32,TXN_9677376,Smoothie,4,4.0,16.0,NaN,In-store,2023-08-15
33,TXN_7710508,UNKNOWN,5,1.0,5.0,Cash,NaN,ERROR
34,TXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-28
36,TXN_6855453,UNKNOWN,4,3.0,12.0,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4,4.0,16.0,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4,2.0,8.0,ERROR,NaN,2023-06-29
40,TXN_2083138,Smoothie,3,4.0,12.0,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4,4.0,16.0,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2,1.5,UNKNOWN,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4,3.0,12.0,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2,1.0,2.0,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3,5.0,15.0,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5,3.0,15.0,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5,3.0,15.0,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3,3.0,9.0,NaN,ERROR,2023-05-02

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [6]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [8]:
df.duplicated().sum()

0

In [7]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [9]:
 df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [10]:
columns = ['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date']

for c in columns:
    print('column name: '+c+' - '+str(len(df[c].unique()))+'\n'+str(df[c].unique())+'\n')

column name: Transaction ID - 10000
['TXN_1961373' 'TXN_4977031' 'TXN_4271903' ... 'TXN_5255387' 'TXN_7695629'
 'TXN_6170729']

column name: Item - 11
['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'UNKNOWN' 'Sandwich' nan
 'ERROR' 'Juice' 'Tea']

column name: Quantity - 8
['2' '4' '5' '3' '1' 'ERROR' 'UNKNOWN' nan]

column name: Price Per Unit - 9
['2.0' '3.0' '1.0' '5.0' '4.0' '1.5' nan 'ERROR' 'UNKNOWN']

column name: Total Spent - 20
['4.0' '12.0' 'ERROR' '10.0' '20.0' '9.0' '16.0' '15.0' '25.0' '8.0' '5.0'
 '3.0' '6.0' nan 'UNKNOWN' '2.0' '1.0' '7.5' '4.5' '1.5']

column name: Payment Method - 6
['Credit Card' 'Cash' 'UNKNOWN' 'Digital Wallet' 'ERROR' nan]

column name: Location - 5
['Takeaway' 'In-store' 'UNKNOWN' nan 'ERROR']

column name: Transaction Date - 368
['2023-09-08' '2023-05-16' '2023-07-19' '2023-04-27' '2023-06-11'
 '2023-03-31' '2023-10-06' '2023-10-28' '2023-07-28' '2023-12-31'
 '2023-11-07' 'ERROR' '2023-05-03' '2023-06-01' '2023-03-21' '2023-11-15'
 '2023-06-10' '2023-02-24' '2023-03-25' '2023-01-15' '2023-04-04'
 '2023-03-30' '2023-12-01' '2023-09-18' '2023-06-03' '2023-12-13'
 '2023-04-20' '2023-04-10' '2023-03-11' '2023-06-02' '2023-11-06'
 '2023-08-15' '2023-10-09' '2023-05-28' '2023-07-17' '2023-04-29'
 '2023-06-08' '2023-06-29' '2023-04-17' '2023-12-22' '2023-01-10'
 '2023-10-02' '2023-02-23' '2023-03-22' '2023-11-03' '2023-03-02'
 '2023-06-26' '2023-05-02' '2023-09-05' '2023-01-08' '2023-03-15'
 '2023-11-25' '2023-12-05' '2023-03-19' '2023-06-27' '2023-04-19'
 '2023-10-07' '2023-09-30' '2023-05-27' '2023-11-18' '2023-10-20'
 '2023-10-03' '2023-10-27' '2023-04-06' '2023-01-31' '2023-12-08'
 '2023-06-19' '2023-12-14' '2023-07-16' '2023-02-22' nan '2023-06-15'
 '2023-12-09' '2023-04-18' '2023-10-29' '2023-04-30' '2023-04-02'
 '2023-05-24' '2023-03-12' '2023-08-16' '2023-09-10' '2023-03-07'
 '2023-08-07' '2023-08-20' '2023-04-15' '2023-07-25' '2023-10-30'
 '2023-12-15' '2023-02-25' '2023-04-03' '2023-10-08' '2023-12-28'
 '2023-08-30' '2023-02-03' '2023-09-12' '2023-05-04' '2023-02-21'
 'UNKNOWN' '2023-03-16' '2023-02-06' '2023-03-29' '2023-06-18'
 '2023-09-23' '2023-01-14' '2023-09-14' '2023-09-16' '2023-04-08'
 '2023-12-19' '2023-07-14' '2023-12-12' '2023-01-05' '2023-01-23'
 '2023-02-20' '2023-12-06' '2023-05-31' '2023-08-11' '2023-09-03'
 '2023-07-11' '2023-06-06' '2023-01-18' '2023-03-23' '2023-01-04'
 '2023-06-23' '2023-08-03' '2023-07-12' '2023-11-02' '2023-07-31'
 '2023-09-19' '2023-02-09' '2023-09-04' '2023-05-21' '2023-07-02'
 '2023-07-10' '2023-11-21' '2023-12-02' '2023-03-13' '2023-08-12'
 '2023-02-16' '2023-04-11' '2023-03-26' '2023-11-01' '2023-07-22'
 '2023-07-26' '2023-02-28' '2023-01-27' '2023-01-19' '2023-04-07'
 '2023-03-20' '2023-12-27' '2023-10-26' '2023-02-18' '2023-05-15'
 '2023-12-10' '2023-04-21' '2023-02-04' '2023-11-12' '2023-08-05'
 '2023-05-10' '2023-07-15' '2023-01-11' '2023-10-01' '2023-04-26'
 '2023-08-25' '2023-03-01' '2023-11-13' '2023-07-09' '2023-05-13'
 '2023-05-18' '2023-01-17' '2023-09-22' '2023-08-22' '2023-07-27'
 '2023-12-30' '2023-12-21' '2023-09-28' '2023-11-16' '2023-04-14'
 '2023-01-03' '2023-01-12' '2023-08-31' '2023-07-07' '2023-09-15'
 '2023-10-21' '2023-09-02' '2023-08-19' '2023-01-06' '2023-10-13'
 '2023-05-29' '2023-05-22' '2023-11-23' '2023-10-15' '2023-11-14'
 '2023-11-26' '2023-12-17' '2023-05-09' '2023-10-22' '2023-06-30'
 '2023-04-25' '2023-02-19' '2023-12-11' '2023-10-12' '2023-07-04'
 '2023-01-28' '2023-10-04' '2023-02-26' '2023-10-11' '2023-02-14'
 '2023-04-28' '2023-09-06' '2023-04-23' '2023-01-22' '2023-03-10'
 '2023-01-09' '2023-12-03' '2023-08-06' '2023-12-29' '2023-02-15'
 '2023-05-25' '2023-10-31' '2023-02-27' '2023-03-03' '2023-09-27'
 '2023-08-18' '2023-12-16' '2023-06-07' '2023-05-12' '2023-07-06'
 '2023-06-20' '2023-08-09' '2023-05-14' '2023-07-18' '2023-10-10'
 '2023-02-02' '2023-08-14' '2023-09-26' '2023-01-13' '2023-10-16'
 '2023-11-17' '2023-12-20' '2023-12-04' '2023-02-08' '2023-09-11'
 '2023-02-01' '2023-02-12' '2023-03-14' '2023-09-29' '2023-04-22'
 '2023-06-13' '2023-12-24' '2023-03-28' '2023-03-06' '2023-02-11'
 '2023-01-30' '2023-04-09' '2023-04-16' '2023-12-23' '2023-03-05'
 '2023-03-24' '2023-07-23' '2023-07-29' '2023-06-05' '2023-10-19'
 '2023-01-07' '2023-11-29' '2023-07-05' '2023-07-20' '2023-05-07'
 '2023-08-10' '2023-10-24' '2023-08-13' '2023-08-28' '2023-06-21'
 '2023-11-10' '2023-10-18' '2023-05-19' '2023-11-09' '2023-06-24'
 '2023-05-11' '2023-12-07' '2023-09-01' '2023-09-25' '2023-06-22'
 '2023-05-30' '2023-04-24' '2023-09-20' '2023-02-07' '2023-05-05'
 '2023-02-10' '2023-11-24' '2023-10-25' '2023-10-05' '2023-07-21'
 '2023-07-08' '2023-03-17' '2023-10-14' '2023-06-28' '2023-09-09'
 '2023-08-21' '2023-07-01' '2023-06-14' '2023-03-09' '2023-11-08'
 '2023-12-26' '2023-09-13' '2023-05-23' '2023-08-24' '2023-04-01'
 '2023-06-09' '2023-08-23' '2023-08-08' '2023-08-27' '2023-05-26'
 '2023-06-16' '2023-12-25' '2023-01-25' '2023-10-23' '2023-05-06'
 '2023-01-29' '2023-08-29' '2023-01-01' '2023-07-24' '2023-04-12'
 '2023-12-18' '2023-09-21' '2023-05-01' '2023-02-05' '2023-01-24'
 '2023-01-02' '2023-06-12' '2023-01-16' '2023-10-17' '2023-03-04'
 '2023-06-17' '2023-03-18' '2023-08-26' '2023-05-17' '2023-11-22'
 '2023-08-17' '2023-11-19' '2023-11-27' '2023-06-04' '2023-09-17'
 '2023-11-04' '2023-11-28' '2023-06-25' '2023-04-13' '2023-01-26'
 '2023-08-04' '2023-05-08' '2023-11-20' '2023-07-13' '2023-09-24'
 '2023-01-21' '2023-03-08' '2023-09-07' '2023-11-30' '2023-08-02'
 '2023-04-05' '2023-08-01' '2023-01-20' '2023-11-11' '2023-02-13'
 '2023-07-30' '2023-02-17' '2023-05-20' '2023-11-05' '2023-03-27'
 '2023-07-03']

### Converting data types to their correct formats.
Numeric columns (Quantity, Price, Total) were converted to numeric types, and Transaction Date was converted to datetime.
The errors='coerce' option ensures invalid entries are turned into NaN for later handling.

In [11]:
df['Quantity'] = pd.to_numeric(df['Quantity'],errors = 'coerce')

df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'],errors = 'coerce')

df['Total Spent'] = pd.to_numeric(df['Total Spent'],errors = 'coerce')

df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], format='%Y-%m-%d', errors='coerce')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

In [13]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

#### Creating a cleaned working copy of the dataset.
From this step forward, I used the variable data to perform cleaning and analysis safely without altering the original dataset.

##### Handling Missing Values Using Logical Relationships

In [15]:
data = pd.DataFrame(df)

In [16]:
for x in data.index:
    if str(data.loc[x,'Total Spent']) == 'nan':
        data.loc[x,'Total Spent']= float(data.loc[x,'Quantity']*data.loc[x,'Price Per Unit'])

In [17]:
data['Total Spent'].isna().sum()

40

In [18]:
pd.DataFrame(data.groupby('Item')['Price Per Unit'].unique())

                               Price Per Unit
Item
Cake                               [3.0, nan]
Coffee                             [2.0, nan]
Cookie                             [1.0, nan]
ERROR     [1.5, 3.0, 5.0, nan, 4.0, 2.0, 1.0]
Juice                              [3.0, nan]
Salad                              [5.0, nan]
Sandwich                           [4.0, nan]
Smoothie                           [4.0, nan]
Tea                                [1.5, nan]
UNKNOWN   [3.0, 1.0, 5.0, 4.0, 1.5, 2.0, nan]

In [19]:
item = {'Cake':3.0,'Coffee':2.0,'Cookie':1.0,'Juice':3.0,'Salad':5.0,'Sandwich':4.0,'Smoothie':4.0,'Tea':1.5}

In [20]:
item.keys()

dict_keys(['Cake', 'Coffee', 'Cookie', 'Juice', 'Salad', 'Sandwich', 'Smoothie', 'Tea'])

In [21]:
for i in data.index:
    if str(data.loc[i,'Price Per Unit']) =='nan' and data.loc[i,'Item'] in item.keys():
        data.loc[i,'Price Per Unit']= float(item[str(data.loc[i,'Item'])])

In [22]:
data['Price Per Unit'].isna().sum()

54

##### In this step, I will handle missing values by recalculating them using existing relationships between columns:

If Total Spent is missing → I will compute it as:
Total Spent = Quantity × Price Per Unit

If Price Per Unit is missing → I will compute it as:
Price Per Unit = Total Spent ÷ Quantity

If Quantity is missing → I will compute it as:
Quantity = Total Spent ÷ Price Per Unit

After applying these formulas, I will re-check for any remaining missing values.
Rows with incomplete or illogical data will be dropped to maintain dataset quality.

In [23]:
for i in data.index:
    if str(data.loc[i,'Price Per Unit']) == 'nan':
        data.loc[i,'Price Per Unit'] = float(data.loc[i,'Total Spent'])/float(data.loc[i,'Quantity'])

In [24]:
data['Price Per Unit'].isna().sum()

6

In [25]:
for x in data.index:
    if str(data.loc[x,'Total Spent']) == 'nan':
        data.loc[x,'Total Spent']= float(data.loc[x,'Quantity']*data.loc[x,'Price Per Unit'])

In [26]:
data['Total Spent'].isna().sum()

23

In [27]:
for i in data.index: 
    if str(data.loc[i,'Quantity']) == 'nan' :
        data.loc[i,'Quantity'] = float(data.loc[i,'Total Spent']/data.loc[i,'Price Per Unit'])

In [28]:
data['Quantity'].isna().sum()

23

In [29]:
data[['Quantity','Price Per Unit','Total Spent']].isna().sum()

Quantity          23
Price Per Unit     6
Total Spent       23
dtype: int64

In [30]:
data[['Quantity', 'Total Spent', 'Price Per Unit']].isna().any(axis=1).sum()

26


##### Removing rows with missing critical numeric values.
Rows missing essential transaction data (quantity, total, or price) were dropped to maintain analysis accuracy.

In [41]:
data.dropna(subset=['Quantity', 'Total Spent', 'Price Per Unit'], inplace=True)

In [42]:
data[['Quantity', 'Total Spent', 'Price Per Unit']].isna().any(axis=1).sum()

0

In [55]:
data[['Payment Method','Location','Transaction Date']].isna().sum()

Payment Method      2570
Location            3257
Transaction Date     460
dtype: int64

In [53]:
data['Item'].isna().sum()

331

##### Dropping rows where item names are missing.
Missing item names indicate incomplete records, which can’t contribute to meaningful analysis.

In [56]:
data.dropna(subset=['Item'],inplace=True)

In [57]:
data['Item'].isna().sum()

0

In [62]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2488
Location            3155
Transaction Date     442
dtype: int64

##### We can process these text columns with the Mode value, but we will be satisfied with considering it a category.

In [65]:
data['Payment Method'].mode()[0]

'Digital Wallet'

In [66]:
data['Location'].mode()[0]

'Takeaway'

In [67]:
data['Transaction Date'].mode()[0]

Timestamp('2023-03-13 00:00:00')

##### Exporting the cleaned dataset.
The final cleaned version is saved for reporting, visualization, or further analysis.

In [68]:
data.to_csv("cleaned_cafe_sales.csv", index=False)